#pragma once

#include "Common/MargAVitException.hpp"

#define SECOND_IN_MILLISECONDS (1000)

#define MILLISECOND_IN_100_NANOSECONDS (10000)

#define SECOND_IN_100_NANOSECONDS (SECOND_IN_MILLISECONDS * MILLISECOND_IN_100_NANOSECONDS)

#define NTSTATUS_SUCCESS (0)

#define PAGE_EXECUTE_ALL (PAGE_EXECUTE | \
						  PAGE_EXECUTE_READ | \
						  PAGE_EXECUTE_READWRITE | \
						  PAGE_EXECUTE_WRITECOPY)
